// AUTO-GENERATED by scripts/gen-migration-list.mjs — do not edit by hand.
// Re-run via `npm run db:generate` or `npm run build`.

export const MIGRATIONS: ReadonlyArray<{ name: string; sql: string }> = [
  { name: "20260528134817_numerous_madrox", sql: "CREATE TABLE IF NOT EXISTS `scores` (\r\n\t`id` integer PRIMARY KEY AUTOINCREMENT,\r\n\t`name` text NOT NULL,\r\n\t`score` integer NOT NULL,\r\n\t`correct` integer NOT NULL,\r\n\t`total` integer NOT NULL,\r\n\t`mode` text NOT NULL,\r\n\t`difficulty` text NOT NULL,\r\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\r\n\t`user_id` text,\r\n\t`game_token` text UNIQUE,\r\n\tCONSTRAINT `fk_scores_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE IF NOT EXISTS `users` (\r\n\t`id` text PRIMARY KEY,\r\n\t`name` text NOT NULL,\r\n\t`first_seen` integer DEFAULT (unixepoch()) NOT NULL,\r\n\t`last_seen` integer DEFAULT (unixepoch()) NOT NULL\r\n);\r\n" },
]
